language: go

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

services:
  - zap-api-go

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - ./pre-commit
  #TODO: enable this when we have test files
  #- go test -cpu=1,2 -v -tags integration ./...